tmp docker based staging environment

diff --git a/install_files/securedrop-app-code/DEBIAN/postinst b/install_files/securedrop-app-code/DEBIAN/postinst
--- a/install_files/securedrop-app-code/DEBIAN/postinst
+++ b/install_files/securedrop-app-code/DEBIAN/postinst
@@ -30,22 +30,25 @@ case "$1" in
     # mode.
     a2dissite 000-default
     a2dissite default-ssl
-    # Stop Apache service before making changes to its AppArmor profile.
-    # If the Apache service is running unconfined, and the profile is
-    # set to "enforce", then apache2 will fail to restart, since it lacks
-    # the ability to send signals to unconfined peers.
-    service apache2 stop
 
-    # If the profile was disabled enabled it.
-    if [ -e "/etc/apparmor.d/disable/usr.sbin.apache2" ]; then
-        rm /etc/apparmor.d/disable/usr.sbin.apache2
+    if ! [ -f /.dockerenv ] ; then
+        # Stop Apache service before making changes to its AppArmor profile.
+        # If the Apache service is running unconfined, and the profile is
+        # set to "enforce", then apache2 will fail to restart, since it lacks
+        # the ability to send signals to unconfined peers.
+        service apache2 stop
+
+        # If the profile was disabled, enable it.
+        if [ -e "/etc/apparmor.d/disable/usr.sbin.apache2" ]; then
+            rm /etc/apparmor.d/disable/usr.sbin.apache2
+        fi
+
+        aa-enforce /etc/apparmor.d/usr.sbin.tor
+        aa-enforce /etc/apparmor.d/usr.sbin.apache2
+
+        # Restart apache so it loads with the apparmor profiles in enforce mode.
+        service apache2 restart
     fi
-
-    aa-enforce /etc/apparmor.d/usr.sbin.tor
-    aa-enforce /etc/apparmor.d/usr.sbin.apache2
-
-    # Restart apache so it loads with the apparmor profiles in enforce mode.
-    service apache2 restart
 
     # cleanup dynamically generated assets
     rm -fr /var/www/securedrop/static/gen/*
